
name: aurex
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  googleapis: ^11.4.0
  shimmer: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  permission_handler: ^12.0.1
  file_picker: ^8.0.0
  logging: ^1.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/welcome_background.png
    - assets/images/bitcoin.png

    - assets/icons/icon_white.png
    - assets/icons/icon_black.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon_black.png

